services:
  - type: web
    name: ashcol-backend
    runtime: docker
    plan: free
    buildCommand: docker build -t ashcol-backend .
    startCommand: docker run -p $PORT:80 ashcol-backend
    envVars:
      - key: APP_NAME
        value: Ashcol_ServiceHub
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: CORS_ALLOWED_ORIGINS
        value: "*"

databases:
  - name: ashcol-db
    plan: free
    databaseName: ashcol_portal
